// Generated by the FlutterFire CLI, project "kanu-rencontres". Regenerate
// with `flutterfire configure` from this directory if apps/platforms change.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` from this directory.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'run `flutterfire configure` from this directory.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ4cSXWxfq37ehY2nuKbqhOGzN4iZxqP4',
    appId: '1:305257104345:android:720c0e2e648872e4e58fc8',
    messagingSenderId: '305257104345',
    projectId: 'kanu-rencontres',
    storageBucket: 'kanu-rencontres.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHIbB0_xcIweyKlx1d_uG3fTRXBxzqBA',
    appId: '1:305257104345:ios:5c3ad9ade4db6748e58fc8',
    messagingSenderId: '305257104345',
    projectId: 'kanu-rencontres',
    storageBucket: 'kanu-rencontres.firebasestorage.app',
    iosBundleId: 'com.kanurencontres.app',
  );
}
